/*
* @name: Arreglos con la informaciona de los pokemones para proyecto final de Técnicas y Prácticas de Programación
* @autores:
 * Rafael Hermida
 * Valentina Caicedo
 * Laura Rojas
* @Descripcion:
 *En el software se estan creando dos arreglos con los nombres, tipo y  descripcion de los pokemones.
*/

/*Importaciones*/
#include <stdio.h>
#include <string.h>

/* Arreglo tipo char donde se almacenan los nombres de los pokemones*/
char nombres[][50] = {"Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard", "Squirtle", "Wartortle",
                     "Blastoise", "Caterpie", "Metapod", "Butterfree", "Weedle", "Kakuna", "Beedrill", "Pidgey",
                     "Pidgeotto", "Pidgeot", "Rattata", "Raticate", "Spearow", "Fearow", "Ekans", "Arbok", "Pikachu",
                     "Raichu", "Sandshrew", "Sandslash", "NidoranM", "Nidorina", "Nidoqueen", "NidoranF", "Nidorino",
                     "Nidoking", "Clefairy", "Clefable", "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff", "Zubat",
                     "Golbat", "Oddish", "Gloom", "Vileplume", "Paras", "Parasect", "Venonat", "Venomoth", "Diglett",
                     "Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck", "Mankey", "Primeape", "Growlithe", "Arcanine",
                     "Poliwag", "Poliwhirl", "Poliwrath", "Abra", "Kadabra", "Alakazam", "Machop", "Machoke", "Machamp",
                     "Bellsprout", "Weepinbell", "Victreebel", "Tentacool", "Tentacruel", "Geodude", "Graveler", "Golem",
                     "Ponyta", "Rapidash", "Slowpoke", "Slowbro", "Magnemite", "Magneton", "Farfetch´d", "Doduo", "Dodrio",
                     "Seel", "Dewgong", "Grimer", "Muk", "Shellder", "Cloyster", "Gastly", "Haunter", "Gengar", "Onix",
                     "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marowak",
                     "Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing", "Rhyhorn", "Rhydon", "Chansey", "Tangela",
                     "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu", "Starmie", "Mr. Mime", "Scyther",
                     "Jynx", "Electabuzz", "Magmar", "Pinsir", "Tauros", "Magikarp", "Gyarados", "Lapras", "Ditto", "Eevee",
                     "Vaporeon", "Jolteon", "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto", "Kabutops", "Aerodactyl",
                     "Snorlax", "Articuno", "Zapdos", "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew"};

/* Arreglo tipo char donde se almacenan el tipo de los pokemones*/
char tipos[][50] = {"Planta-Veneno", "Planta-Veneno", "Planta-Veneno", "Fuego", "Fuego", "Fuego-Volador", "Agua", "Agua",
                     "Agua", "Bicho", "Bicho", "Bicho-Volador", "Bicho-Veneno", "Bicho-Veneno", "Bicho-Veneno", "Normal-Volador",
                     "Normal-Volador", "Normal-Volador", "Normal", "Normal", "Normal-Volador", "Normal-Volador", "Veneno", "Veneno", "Eléctrico",
                     "Eléctrico", "Tierra", "Tierra", "Veneno", "Veneno", "Veneno-Tierra", "Veneno", "Veneno",
                     "Veneno-Tierra", "Hada", "Hada", "Fuego", "Fuego", "Normal-Hada", "Normal-Hada", "Veneno-Volador",
                     "Veneno-Volador", "Planta-Veneno", "Planta-Veneno", "Planta-Veneno", "Bicho-Planta", "Bicho-Planta", "Bicho-Veneno", "Bicho-Veneno", "Tierra",
                     "Tierra", "Normal", "Normal", "Agua", "Agua", "Lucha", "Lucha", "Fuego", "Fuego",
                     "Agua", "Agua", "Agua-Lucha", "Psíquico", "Psíquico", "Psíquico", "Lucha", "Lucha", "Lucha",
                     "Planta-Veneno", "Planta-Veneno", "Planta-Veneno", "Agua-Veneno", "Agua-Veneno", "Roca-Tierra", "Roca-Tierra", "Roca-Tierra",
                     "Fuego", "Fuego", "Agua-Psíquico", "Agua-Psíquico", "Eléctrico-Ácero", "Eléctrico-Ácero", "Normal-Volador", "Normal-Volador", "Normal-Volador",
                     "Agua", "Agua-Hielo", "Veneno", "Veneno", "Agua", "Agua-Hielo", "Fantasma-Veneno", "Fantasma-Veneno", "Fantasma-Veneno", "Roca-Tierra",
                     "Psíquico", "Psíquico", "Agua", "Agua", "Eléctrico", "Eléctrico", "Planta-Psíquico", "Planta-Psíquico", "Tierra", "Tierra",
                     "Lucha", "Lucha", "Normal", "Veneno", "Veneno", "Tierra-Roca", "Tierra-Roca", "Normal", "Planta",
                     "Normal", "Agua", "Agua", "Agua", "Agua", "Agua", "Agua-Psíquico", "Psíquico-Hada", "Bicho.Volador",
                     "Hielo-Psíquico", "Eléctrico", "Fuego", "Bicho", "Normal", "Agua", "Agua-Volador", "Agua-Hielo", "Normal", "Normal",
                     "Agua", "Eléctrico", "Fuego", "Normal", "Roca-Agua", "Roca-Agua", "Roca-Agua", "Roca-Agua", "Roca-Agua",
                     "Normal", "Hielo-Volador", "Eléctrico-Volador", "Fuego-Volador", "Dragón", "Dragón", "Dragón-Volador", "Psíquico", "Psíquico"};

/* Arreglo tipo char donde se almacenan la descripcion de los pokemones*/
char descripcion[][500] = {
        "Es un Pokémon cuadrúpedo de color verde y manchas más oscuras de formas geométricas",
        "Posee un color azulado más vivo que su preevolución. Sus ojos adquieren un leve tono violeta y sus pupilas se vuelven negra",
        "El capullo de su lomo se abre completamente, dejando ver una enorme flor rosada y unas hojas semejantes a las de palmera",
        "Es un pequeño lagarto bípedo. Sus características de fuego son resaltadas por su color de piel anaranjado y su cola con la punta envuelta en llamas",
        "Es un gran lagarto bípedo que posee como característica general una llama en la punta de su cola",
        "Viven en el Valle Charirrífico. Les gusta vivir en lugares altos y calientes, por lo que se encuentran en muchas ocasiones cerca de volcanes",
        "Habita tanto aguas dulces como marinas. Son pequeñas tortugas color celeste con caparazones color café; o rojas en algunos casos, con una cola enrollada que los distingue",
        "Es una tortuga de color azul índigo, con una pomposa cola, orejas con forma de aleta, y un caparazón de color café oscuro",
        "Es una enorme tortuga bípeda, que puede extender unos poderosos cañones situados en su espalda para disparar potentes chorros de agua, con la fuerza suficiente para quebrar muros de cemento o metales delgados",
        "Tiene pequeños pies con ventosas en sus extremos que le permiten trepar árboles y paredes sin mayor esfuerzo",
        "Se asemeja a una gran crisálida de color verde intenso, y solamente sus ojos son visibles",
        "El diseño de sus ojos es básicamente igual al de una mariposa común. Su cuerpo está dividido en dos partes: cabeza y tronco",
        "Tiene la forma de un gusano con un cuerno que segrega veneno, que puede utilizar para defenderse de sus depredadores",
        "Está basado en una pupa. Es una especie de capullo muy duro, de color amarillo, con dos enormes ojos de color negro. Habita en zonas de hierba alta y en las zonas arboladas como en bosques",
        "Comparte muchas características con las avispas y abejas, de forma que también es parecido a Combee y Vespiquen. Es bastante territorial: si su nido es molestado comenzarán a atacar en un furioso enjambre",
        "Son de naturaleza amistosa y bastante valientes. Son Pokémon calmados, y atraer su atención es fácil",
        "Son aves grandes, quizá basadas en las águilas pescadoras y los Merlín, con talones afilados, una cola de plumas rojas y amarillas, así como una cresta roja en su cabeza",
        "Su habilidad de vuelo es increíble, pudiendo alcanzar más de un kilómetro de altura y llegar al doble de la velocidad del sonido. Es capaz de detectar a una presa incluso a 1.000 metros de altura",
        "Extremadamente común y se reproduce muy rápido, por lo que el contacto visual con uno de ellos indica la presencia de más de 40 de ellos en el área",
        "Tiene la piel marrón clara y una larga cola. Sus colmillos son grandes, duros y firmes, y le permiten roer cualquier cosa",
        "Su pico es pequeño, el cual usa para atrapar a sus presas. Sus alas son de color rojizo y sus puntas tienen un tono más claro. Las patas tienen garras para poder agarrar a sus presas",
        "Se le reconoce por tener un pescuezo y un pico largo que le permiten cazar en tierra y en el agua. Tiene una gran habilidad moviendo el fino pico para atrapar a sus presas",
        "Al ser una serpiente, le es fácil moverse por casi todo tipo de lugares y escabullirse en cualquier momento. Es muy silenciosa y sigilosa, es difícil saber cuando está al acecho. Su longitud crece a medida que envejece",
        "Este Pokémon es venenoso y habita en pantanos, bosques, etc. Sus músculos son capaces de estrujar bidones de hierro",
        "Almacena una gran cantidad de electricidad en sus mejillas. Estas parecen cargarse eléctricamente durante la noche mientras duerme. Las mejillas de Pikachu también pueden ser recargadas mediante una descarga eléctrica, como se ha podido observar en algunos episodios del anime",
        "Tiene un pelaje anaranjado, una cola oscura y gruesa como un cable de tendido eléctrico que termina en forma de rayo y totalmente plana, que además puede soportar grandes cargas",
        "Es una criatura pequeña, amarilla y de apariencia similar a un roedor, cubierto de escamas duras y con garras afiladas. Sus ojos son grandes y negros",
        "Se alimenta de lo que logra cazar en el desierto y el rocío que se forma en sus escamas durante la noche es su principal fuente de agua",
        "Cuando se enfurece, libera una horrible toxina de sus cuernos. Son unos Pokémon muy tranquilos y dóciles y parecen roedores al igual que su contraparte",
        "Es muy similar a Nidorino a pesar de que no tenga cuerno. Puede enfadarse tanto o más que este ya que sabe defenderse bien con sus púas venenosas. Tiene un oído tan fino dado el considerable tamaño de sus orejas",
        "No puede criar huevos al no pertenecer a ningún grupo huevo; vive en las praderas y tiene unas escamas que le ayudan a hacer ataques de gran poder y a la vez le proporcionan gran defensa",
        "Desarrolla músculos para el movimiento de sus orejas. Gracias a ello sus orejas pueden moverse libremente hacia cualquier dirección, por esto, ni el más mínimo de los sonidos se le escapa",
        "Su cuerno es un arma muy útil, pues es casi tan duro como el diamante y segrega un potente veneno. Pero el cuerno también sirve para hacer ataques físicos tales como Picotazo o Ataque furia",
        "Suele ser agresivo. Posee un poderoso cuerno que le sirve para hacer grandes ataques. Por esto, es conocido como el Pokémon del poderoso taladro. De igual manera, su cola es tan poderosa que puede derribar una torre eléctrica de un golpe",
        "Es rosa con pequeños brazos y un tierno amigo Pokémon. Puede tener una apariencia engañosa, puesto que tiene combinaciones severas como los potentes fuerza lunar y puño meteoro",
        "Es uno de los Pokémon menos comunes. Clefable es muy tímido, ya que corre a esconderse cuando siente a alguien cerca. Debe ser bien cuidado por su entrenador para que se gane su confianza. Muy rara vez ha sido visto por humanos, y es considerada un hada de buena suerte",
        "Cuando nacen tiene una cola, la cual es blanca como su evolución Ninetales. Al crecer esta se torna rojo oscuro como el resto del cuerpo, se divide en seis y se convierte en bellos rizos",
        "Ninetales es un Pokémon muy parecido a un zorro albino, su pelaje es de color dorado y las puntas de sus colas de un color amarillo mostaza o naranja, que al paso de los años va cambiando de color",
        "Jigglypuff tiene un cuerpo circular, rosa, esponjoso y acentuado con pequeños apéndices, así como una pequeña mota de cabello en su cabeza, tiene unos enormes ojos azules y unas orejas puntiagudas",
        "Wigglytuff es un Pokémon relativamente grande y con forma de globo. Es de color rosa casi en su totalidad, exceptuando su vientre, que es de color blanco. Tiene un par de orejas de conejo, una mota de pelo rosa entre ellas, y ojos grandes y de color azul. Es relativamente parecido a su pre-evolución, Jigglypuff.",
        "Está basado en un micromurciélago. A pesar de ser ciego, Zubat puede conocer el ambiente donde se encuentra gracias a las ondas supersónicas que transmite desde su boca y que rebotan hasta su oído, con las cuales cazan a sus presas. Este fenómeno es conocido como ecolocalización.",
        "Los Golbat usan ultrasonidos con la función de detectar a sus presas y pillarlas por la espalda. Una vez cazadas, se alimentan hasta hartarse, pero luego están algo indefensos, ya que sus movimientos son más torpes, por lo que debe tener cuidado. Son normalmente preferidos por los villanos, que además también utilizan a su preevolución Zubat y a su evolución Crobat",
        "Oddish está inspirado en un rábano, pero tambien recuerda a la mandrágora. Oddish es un pequeño y muy común Pokémon que pasa el día bajo tierra dejando al descubierto únicamente las hojas de la cabeza; por esto mucha gente no nota su presencia.",
        "El nombre de este Pokémon proviene de la palabra en ingés gloom que significa triste o sombrío por su expresión, la cual parece imitar los sentimientos anteriormente dichos. También puede ser una conjunción de las palabras inglesas gloom y bloom",
        "Vileplume posee los pétalos de flor más grandes del mundo. Son muy pesados, por lo cual le cuesta mantener la cabeza erguida, así como moverse a velocidad. Esto agregado a sus brazos pequeños le impiden desenvolverse en el combate cuerpo a cuerpo, sin embargo esta carencia es indiferente",
        "Este Pokémon habita en cuevas o lugares oscuros, donde el alimento es escaso. Se alimenta de insectos más pequeños que él. A veces también recurre a alimentarse de las dos setas-hongo que lleva en su espalda llamadas tochukaso",
        "El hongo que lleva en su espalda es mucho más grande que él y además tiene grandes propiedades curativas, al igual que sus esporas, que se utilizan para crear medicamentos. Cuando se siente amenazado se defiende con sus enormes tenazas y liberando esporas de su enorme hongo. ",
        "Venonat es un Pokémon de tipo bicho. Come insectos más pequeños que él. Caza a sus presas por la noche, por lo que es raro verlo durante el día. ",
        "Vive en bosques, por lo general en pequeños grupos guiados por el Venomoth más grande o de mayor colorido en las alas. Nunca ataca a sus presas; estas caen al ser guiadas por sus vistosos colores en las alas para después ser devoradas tranquilamente. ",
        "Diglett es un Pokémon con forma de topo. Pasa la mayor parte de su vida bajo tierra. Su cuerpo es de color marrón y tiene forma de dedo. A pesar de no superar los 20 cm de altura, si se juntan en grupo pueden ser muy destructivos, arrasando presas y construcciones en los bosques. ",
        "La biología de este Pokémon no está nada clara. Algunas fuentes afirman que es un ser que tiene tres cabezas, mientras en otros lados se especifica que son tres hermanos Diglett que cavan juntos. No es posible verificar una u otra porque al igual que con su preevolución, Diglett,",
        "Es un Pokémon con apariencia de gato, y está basado en el Maneki-neko (gato de la suerte japonés). En su cabeza porta un amuleto en forma de moneda. Se trata de una antigua moneda japonesa hecha de oro llamada Koban, símbolo de la buena fortuna en Japón.",
        "Su nombre proviene simplemente de una raza de gato en la que podría estar inspirado, persian cat (gato persa en español), aún así, no comparten gran parecido. Más bien, tiene mayor parecido a un felino salvaje (puma) o a un siamés.",
        "Se alimenta de peces que quedan atontados en las rocas o que accidentalmente chocan con él. Cuando la hembra queda preñada y pone un huevo, el funcionamiento de la familia cambia. La hembra permanece en su hábitat y el macho se encarga de velar por ella y por su cría.",
        "Golduck es la forma evolucionada de Psyduck. Este Pokémon puede usar ataques tipo psíquico y agua, siendo su movimiento más poderoso capaz de aprender hidrobomba. Además, gracias a sus brazos y aletas Golduck es el nadador más rápido de todos los Pokémon, ",
        "Los Mankey son sigilosos y ágiles. Si alguno se llega a extraviar del grupo, se vuelve rabioso ya que no soporta la soledad. Incluso podrían atacar a la primera persona o Pokémon que se topen",
        "Primeape es un pokemon de carácter altamente irritable. No duda en atacar a cualquier cosa y sin ningún motivo. Si alcanza el estado de furia, es muy peligroso acercarse a él debido a que no distingue entre amigos y enemigos. Manifiesta sus emociones con violencia. Demuestra el afecto por su Entrenador dándole una paliza",
        "Es muy agradable, cariñoso, leal y temerario; tiene un gran sentido del honor. Para ahuyentar al enemigo se pone a ladrar y a lanzar fuego. También es conocido por su gran lealtad hacia su entrenador, a quien reconoce por su voz y olor. Si Growlithe perdiera el olfato y el oído le seria imposible reconocer a su entrenador",
        "Su llama puede alcanzar los 3000 grados celsius. Su pelaje es suave, de color naranja a rayas negras y con una cola anaranjada, cercano al color blanco. Es de naturaleza valiente y leal además de majestuosa. Tiene un gran sentido del honor.",
        "Poliwag es un Pokémon de tipo agua. Parece estar basado en el renacuajo de Costa Rica. La espiral que posee en su vientre corre hacia la derecha. Su cola plana le permite dar fuertes bofetadas rápidamente.",
        "Poliwhirl puede estar todo un mes fuera del agua y suda para mantenerse húmedo. Puede utilizar ataques de lucha pero son pocos. Prefiere utilizar los ataques de agua",
        "Cuando Poliwhirl evoluciona en Poliwrath su semblante cambia totalmente, ganando el subtipo lucha cosa que lo hace mucho más intimidante. Un Pokémon que se caracteriza por su alto rendimiento físico, capaz de nadar mares ida y vuelta sin agotarse, el luchador perfecto ya que un practicante de artes marciales debe entrenar mucho para pulir sus habilidades",
        "Abra está probablemente basado en un Fennecus zerda, un fénec, al igual que Fennekin. Además, dispone de una coraza marrón que lo protege. Tiende a tener los ojos cerrados y por esto mismo es difícil saber si está dormido o si simplemente está utilizando sus poderes telequinéticos",
        "Kadabra no es muy fuerte a lo que respecta a ataques físicos, por el contrario, psíquicamente se podría decir que es uno de los mejores luchadores, además de ser muy veloz, lo que lo convierte en un Pokémon bastante bueno.",
        "Alakazam es un Pokémon tipo psíquico, que se caracteriza por un gran poder mental. Posee dos cucharas, una en cada mano, que aumentan sus poderes psíquicos. Curiosamente a diferencia de su preevolución Kadabra, Alakazam tiene dos cucharas en vez de una. En el anime Alakazam crea los ataques con sus cucharas y después ataca al enemigo",
        "Este Pokémon se dedica diariamente a entrenar y fortalecer sus músculos para ser cada vez más fuerte, por lo cual levanta pesados objetos o enormes rocas, o incluso Pokémon extraordinariamente pesados, como Geodude o Graveler",
        "Su musculoso cuerpo es tan fuerte que usa un cinturón anti-fuerza para controlar sus poderosos ataques y su abrumadora fuerza. Nadie le ha quitado el cinturón nunca. Los entrenados músculos de Machoke son tan fuertes como 200 hombres juntos.",
        "Machamp es uno de los Pokémon de tipo lucha más fuertes, dominando cualquier tipo de arte marcial; es capaz de dar 1000 golpes en tan solo dos segundos, y si toma al rival por los pies con sus cuatro brazos, lo lanzará lo más lejos posible, ganando fácilmente el combate",
        "Su cuerpo consiste en un tallo que es muy delgado y flexible, lo cual le permite doblarse y balancearse rapidamente para prevenir cualquier ataque. A causa de esto, tiene una gran velocidad al momento de atrapar insectos",
        "Tiene forma de campana, predominando un fuerte color amarillo en su cuerpo. Tiene dos hojas afiladas las cuales ocupa para comer, ya que si su presa no cabe por entero en su boca la rebana en pedazos.",
        "Está inspirado en la planta carnívora nepenthes. Cuando ve algo que le llama la atención, salta sobre él y con el ácido de su boca, que huele a algo parecido a miel, lo derrite para tragárselo. Come cualquier insecto Pokémon sin importar que sea venenoso, ya que sus potentes ácidos estomacales lo disolverán eliminando el veneno e incluso",
        "Está basado en una medusa con rasgos cefalópodos, aunque el hecho de que tenga ojos también podría deberse a que de todas las medusas estuviera basado en una avispa de mar",
        "Debilita a las presas que atrapa con sus tentáculos, los cuales pueden ser libremente extendidos y reducidos a su voluntad. Puede atrapar 80 presas a la vez, una con cada tentáculo",
        "Los Geodude habitan en las montañas que escalan a pulso con sus fuertes brazos. Cuando quieren dormir, se entierran a medias en el suelo, y por mucho que lo pisen mientras duerme, no se despertará. Por el contrario, si alguien se tropieza con él mientras está despierto, se enfadará y agitará sus puños con agresividad.",
        "Este Pokémon tiene la apariencia de una enorme roca con 4 brazos. Baja desde las montañas y aplasta las rocas que encuentra a su paso. Su embestida es sumamente poderosa.",
        "A diferencia de su pre-evolución, Golem no posee 4 brazos. Vive en las laderas de las montañas. Cuando hay terremotos, baja por las montañas rodando. Para evitar aplastar casas, se han cavado unos surcos para guiarlos cuando bajan.",
        "Al nacer es un poco débil pero con el tiempo se fortalece. Tiene unas patas muy fuertes, que se desarrollan desde que nace, sus pezuñas son más fuertes que el diamante.",
        "Este Pokémon vive en praderas muy extensas, campos y llanuras y suele ser algo solitario. En cuanto a velocidad se refiere, puede competir con Dodrio y su velocidad oscila entre 200 y 240 km/h, ya que es muy ágil, aunque no es el Pokémon más rápido.",
        "La cola de Slowpoke segrega una sustancia muy dulce, tanto así que se le considera un manjar; en la región de Johto se les caza de manera ilegal. A pesar de ello, la dulce sustancia no tiene ningún valor nutritivo",
        "El Shellder de la cola de Slowbro se alimenta del dulce jugo que desprende y aprovecha la situación para poder trasladarse por tierra, y gracias al contrapeso que produce, Slowbro puede mantenerse erguido sobre sus patas traseras para moverse con mayor libertad",
        "Magnemite es un Pokémon de carácter inorgánico. Su cuerpo está construido de materiales superconductores de campos magnéticos así como almacenes de energía como el Litio, el Cadmio y el Níquel",
        "Cuando las cargas de atracción de los Magnemite son demasiado fuertes, tres de ellos se unen para dar lugar a un Magneton, aunque algunos científicos creen que al evolucionar se divide como una célula, lo cuál explicaría que cuando sale uno variocolor lo sean las tres unidades",
        "Se caracteriza por llevar siempre consigo un puerro o ramita de cebolla cambrai, el cual usa para muchas cosas como hacer su nido, para luchar, defenderse, o en raros casos como comida de emergencia.",
        "Es un ave Pokémon de dos cabezas. Tiene forma de avestruz, kiwi (un ave parecida) o ñandú. Es un Pokémon que no tiene muy buen vuelo pero lo compensa con su gran velocidad",
        "Suele habitar en llanuras muy extensas. Es tan rápido que cuando está en su máxima velocidad se ve como un borrón. Le encanta competir con otros Dodrio. Algunos piensan que las cabezas representan la tristeza, la dicha y la ira. Si sus cabezas se enfadan unas con las otras, no pararán de pelear en todo el día",
        "Vive en mares y lagos aunque la mayor población conocida es en las Islas espuma donde desarrollan su vida en la tranquilidad de las cavernas. Su cuerno es lo suficientemente resistente como para romper el hielo de los icebergs. ",
        "A Dewgong le gusta estar en sitios fríos y húmedos, su pelaje blanco le ayuda a camuflarse en la nieve. Es un Pokémon que muchas veces ayuda a la gente, ya que es muy bondadoso, generoso y por lo general transporta personas vía marítima en su espalda. ",
        "Grimer nace de lodo alterado al filtrarse en el agua los rayos X reflejados por la luna. Aparece en zonas asquerosas. Crece y se alimenta de sustancias de lo más desagradables, absorbiendo los residuos tóxicos de las fábricas. ",
        "Muk está hecho de desechos tóxicos y lodo, despide un fétido olor que aleja a sus oponentes. A pesar de su aspecto y el fétido hedor que desprende, Muk es un Pokémon muy cariñoso, tanto entre ellos, como con sus entrenadores, cogiéndoles rápidamente confianza e incluso en ciertas ocasiones, abrazándolos.",
        "Shellder está basado en una ostra con su perla. Su cabeza es una esfera como la perla, de color negra con grandes ojos y una lengua, que siempre mantiene fuera y está protegida por su concha de color morado, la cual tiene cuatro pinchos.",
        "Cloyster vive en mares y lagos profundos. Es tranquilo, pero cuando se pone a luchar es capaz de destrozar a sus enemigos. Su gran punto fuerte es su resistente concha, que puede soportar hasta el impacto de bombas.",
        "Está hecho de una masa negra gaseosa con un aura de gas violeta a su alrededor la cual es venenosa y asfixiaría a la mayoría de mortales. Gastly se asemeja al cuerpo de un Hitodama (término del folclore japonés que hace referencia a la aparición de las almas cuando abandonan el cuerpo antes de ir al otro mundo).",
        "Haunter es un Pokémon que tiene manos a pesar de no tener brazos. Está compuesto por gas y es por eso que flota. Es de color morado y por su fisiología puede atravesar objetos sólidos",
        "Gengar es un Pokémon con extremidades pequeñas. Tiene una personalidad siniestra y tenebrosa, sobre todo en estado salvaje. Se dice que por las noches sale a espantar y perder a los viajeros para robar su alma",
        "Onix es uno de los Pokémon más curiosos por su aspecto físico, teniendo forma similar a la de una lombriz hecha de roca. A pesar de su gran tamaño (más de 8 metros) pesa muy poco. Investigaciones recientes demostraron que en realidad Onix es hueco por dentro, exceptuando la zona de la cabeza, donde se encuentra su cerebro imantado.",
        "Parecido a un tapir malayo, este Pokémon es de gran utilidad para las personas que padecen insomnio. Es capaz de dormir a una ciudad entera con su poder mental.",
        "Por su forma, podría guardar relación con un mono narigudo, aunque simplemente puede considerarse que es de aspecto humanoide",
        "Krabby es un Pokémon cangrejo, misterioso y excéntrico. Este Pokémon camina de lado como un cangrejo y observa de medio lado, nunca mira a algún Pokémon o humano directamente, sólo de reojo. ",
        "Su nombre proviene de las palabras del inglés king, de king crab (cangrejo rey), y fiddler, de fiddler crab (cangrejo violinista), dos especies de cangrejo en las cuáles está basado. Su nombre en japonés es igual",
        "Voltorb tiene la forma de una Poké Ball, es decir, una esfera dividida en dos partes: blanca la parte de abajo y roja la de arriba. También se puede observar que cuenta con un par de ojos, característicos del anime, y que lo dotan de una expresión de enfado",
        "Su nombre viene de la palabra en inglés electrode (electrodo). También puede ser una combinación de las palabras en inglés electric (eléctrico) y explode (explotar)",
        "Aunque parecen huevos, en realidad son frutos. Tanto para estar juntos como defenderse usan sus poderes psíquicos y se comunican por medio de la telepatía. Sorprende también que para su tamaño, a veces demuestra gran fuerza.",
        "El cuerpo de Exeggutor tiene la apariencia de una palmera. Para que no haya rivalidades, sus cabezas están en completa armonía para que así no peleen entre sí.",
        "Cubone es un Pokémon pequeño y solitario, porque su madre muere cuando él nace, por eso lleva el cráneo de su madre en la cabeza. Se cree que el hueso que lleva como arma es el fémur de su madre, pero todavía no se sabe. Muchas veces ve un parecido de ella en la luna llena y llora. Las manchas en la calavera están hechas por lágrimas que derrama. ",
        "Tras evolucionar de Cubone, su cráneo y la coraza ósea que lleva sobre la cabeza se fusionan, formando una nueva coraza mucho más cómoda y resistente que la anterior",
        "Hitmonlee es un Pokémon basado en Jamila, personaje de Ultraman. Se caracteriza por ser un Pokémon especialista en patadas, las cuales son increíblemente fuertes y veloces. Debido a su gran elasticidad puede dar patadas casi en cualquier posición en la que esté hacia cualquier dirección",
        "A diferencia de Hitmonlee, Hitmonchan es un maestro de los puños con los cuales consigue noquear a cualquier oponente. Su destreza con los golpes ha logrado que pueda aprender puñetazos de todas clases, incluyendo los elementales, entre otros",
        "Lickitung es un Pokémon voluminoso y bípedo con algunas características de camaleón. Tienen una larga e hinchada cola parecida a la de una ardilla y una larguísima lengua. Posiblemente este Pokémon este basado en una tiliqua o escinco de lengua azul con el que comparte muchas características de su morfología como la gran lengua",
        "El cuerpo de Koffing está compuesto de un barro mugriento, seco y rugoso que le hace tener forma de bomba y lleva un extraño símbolo similar al que llevan las sustancias venenosas que sirve para alertar a los agresores de que es venenoso",
        "Weezing y Koffing suelen vivir en lugares muy contaminados, ya sea en vertederos, pantanos o en ciudades industriales. Hasta hace no mucho tiempo Weezing era uno de los Pokémon con peor fama que existían. La gente los cazaba con odio, creyéndolos trasmisores de horribles enfermedades y pestes",
        "La forma de Rhyhorn se asemeja mucho a la de un rinoceronte. Está todo hecho de piedra, anda en cuatro patas (a diferencia de sus evoluciones)",
        "Este Pokémon de carácter fuerte y algo violento. Vive en montañas, valles, y, raramente, en desiertos. Puede hacer girar su cuerno como un taladro para destruir montañas enteras. Su cuerpo es tosco y muy seco. ",
        "Es un Pokémon raro de capturar, su carácter amable hace que quiera ayudar siempre a la gente de buen corazón. Por eso, un sitio donde se pueden encontrar muchos Chansey es en los hospitales, donde ayudan a las enfermeras Joy a cuidar los Pokémon heridos",
        "Este Pokémon está cubierto de enredaderas azules gruesas que ocultan su rostro tanto que sólo sus ojos se pueden ver. Las enredaderas le dan una forma redonda, aunque no se sabe cómo se ve sin ellas. Tiene dos patas rojas en forma de botas.",
        "Kangaskhan posee en su estómago una gran bolsa (marsupio) para cuidar a sus crías, aunque no siempre las lleva ahí. Es un Pokémon con un gran instinto maternal",
        "Su tinta está compuesta por barro y algas, por lo que debe comer eso de vez en cuando. Le gusta mezclarse con las personas y otros Pokémon acuáticos, aunque es muy miedoso. Si siente que está en peligro escupirá toda su tinta a su rival para huir lo más rápido que pueda. ",
        "El único objetivo de Seadra es fortalecerse, tiene el poder para disparar un chorro de agua tan fuerte o más que la manguera de los bomberos y con una asombrosa precisión capaz de atinarle a objetos en movimiento a gran velocidad lo que utiliza para derribar algunos insectos",
        "Goldeen es un elegante pez Pokémon que habita numerosos ríos y lagunas; pero a pesar de su aspecto es muy fuerte y peleón. Es capaz de aprender un ataque fulminante, perforador, que deja K.O en un solo golpe",
        "El cuerno que tiene en su cabeza le sirve para cavar sus nidos, donde pone sus huevos, pero también lo usa para atacar a aquellos que se acerquen a su familia. Es muy protector de sus huevos, el macho y la hembra se turnan para cuidar su nido y sus huevos durante alrededor de un mes",
        "Staryu es un Pokémon basado en una estrella de mar. Su cuerpo es de un color amarronado, con una formación de oro en el centro de su cuerpo. En el mismo centro de su cuerpo tiene un órgano exterior que se asemeja a una joya roja llamada \"la base\". Hay un lazo de oro alrededor de una de sus patas. ",
        "Starmie está posiblemente basado en un equinodermo asteroideo con más de cinco puntas, como por ejemplo Pycnopodia helianthoides, aunque hay muchas más. No obstante, en realidad parece la unión de dos estrellas con cinco puntas, dado que los brazos no surgen de un mismo cuerpo central, sino de dos, uno que está en la parte delantera y otro en la trasera",
        "Su nombre inglés son dos palabras, Mr., abreviación de mister (señor) y mime (mimo, por su inspiración en los mimos), por lo que su nombre puede interpretarse como Señor Mimo",
        "A este Pokémon se le conoce como el Pokémon mantis guerrera. Armado con unas potentes y afiladas guadañas y unas alas poco desarrolladas este Pokémon es extremadamente veloz, se dice que sus cuchillas se vuelven más afiladas al cortar objetos duros",
        "Jynx se caracteriza por tener un parecido especial con los humanos, especialmente a una mujer. Le encanta moverse y bailar con ritmo y gracia. Cuando Jynx danza, inspira a otras personas a imitarla. Sus labios son la parte más sensible de su cuerpo",
        "Electabuzz es un Pokémon bastante violento y fuerte. No se deja ver mucho en hábitats distintos a las plantas de energía, en las que se alimenta de la electricidad que se genera en ellas. También se le puede encontrar en sabanas despejadas",
        "Magmar es un Pokémon constituido básicamente por fuego, y sus ataques son mucho más fuertes que los de su preevolución, pudiendo llegar a temperaturas el doble de elevadas. El fuego es su sistema para recuperarse ya que cierra totalmente sus heridas después de intensos combates. ",
        "Pinsir es un Pokémon insecto que habita en los bosques que contienen árboles de savia, ya que se alimenta de ésta. Es un Pokémon con un temperamento fuerte, que posee unas largas pinzas afiladas en la parte superior de su cabeza que permite el corte de las ramas, y con su boca que contiene más de 20 dientes pequeños",
        "Es un Pokémon que fácilmente se le pueden ver en llanuras. Normalmente se encuentra en numerosas manadas de decenas de individuos. Tiene tres colas que le ayudan a ganar gran velocidad y mantener el equilibrio.",
        "Magikarp, al igual que su evolución Gyarados, está inspirado en una antigua leyenda china conocida como Li yu tiao Long men, cinco caracteres que significan literalmente la carpa salta sobre la Puerta del Dragón.",
        "Físicamente, Gyarados se asemeja mucho a un dragón marino, como el Dragón chino. A diferencia de Magikarp, su cuerpo es principalmente azul, la parte inferior es amarillo claro y sus aletas dorsales son blancas.",
        "Lapras podría estar inspirado bien en un plesiosaurio (una especie de lagarto marino extinto en el Cretácico) o bien en Nessie, (el monstruo del Lago Ness), incluso tiene parecido a una tortuga acuática; esto es por su coraza en la espalda y la forma que adoptan sus aletas",
        "Ditto toma la forma de una figura amorfa color violeta. Es probable que, en el caso de estar este Pokémon ligeramente basado en alguna forma de vida animal, sea en un placozoo. Da la impresión que no tiene cerebro u órganos vitales, pero actúa y se comunica como cualquier Pokémon normal",
        "El nombre de Eevee proviene de la palabra inglesa evolution, que significa evolución en español, debido a la multitud de evoluciones que posee. ",
        "Si a Eevee se le expone a una piedra agua y evoluciona en Vaporeon, será un excelente nadador, capaz de hacerse invisible en el agua y tendrá grandes habilidades acuáticas. Se volverá tranquilo, maduro, crecerá con mucho asomo su sabiduría, ya que sabe tanto sobre las cosas de tierra como las del mar.",
        "Jolteon está inspirado en un zorro. Su pelaje le permite captar y almacenar gran cantidad de electricidad estática del ambiente, con lo que se eriza y endurece formando púas, que puede usar para concentrar y dirigir sus ataques eléctricos contra el rival. ",
        "Si se le expone a Eevee una piedra fuego evolucionara a Flareon, convirtiéndose en un Pokémon de Fuego, su nobleza y su exuberancia crecerán deprisa, es el más fiel de todos, pero también su pereza será notable a menos que no se le mime tanto",
        "Porygon posee una forma física similar a la de un pato o grulla y es el primer Pokémon creado artificialmente. Porygon es un Pokémon que despierta cierta controversia en los entrenadores de la vieja escuela, ya que el hecho de que sea un Pokémon creado por el hombre y que pueda comprarse en algunas tiendas causa cierta mezcla de miedo/rechazo",
        "Se le creía extinto pero eso quedó denegado ya que en varios laboratorios han podido ser resucitados a partir del Fósil hélix. También en uno de los capitulos de la serie se muestra toda una colonia viva y por eso se cree que siguen habitando algunos lugares",
        "Omastar es un Pokémon extinto, por lo cual no es posible atraparlo en estado salvaje, la única manera de obtenerlo es mediante la evolución de Omanyte o reviviendolo desde un fósil. Se dice que este Pokémon está extinto a causa de que su caparazón es demasiado pesado, lo cual lo volvía lento y le era difícil atrapar a su presa",
        "Posee un caparazón en forma de domo (es resucitado a partir del fósil domo) con el que se defendía de sus depredadores, pero si se le derribaba de costado era presa fácil, es parecido a los trilobites (artrópodos extintos en el Pérmico).",
        "Kabutops esta basado en un Trilobites, una clase de artrópodos prehistóricos que no poseen parientes vivos actuales. Se extinguieron hace 250 millones de años aproximadamente",
        "Aerodactyl era un Pokémon carnívoro, atacaba con sus agudos colmillos al cuello de su presa, aunque de vez en cuando también comía bayas. Sus alas tenían potentes músculos para poder volar, sin embargo, no era muy buen volador por lo que le resultaba difícil atrapar Pokémon al vuelo. ",
        "Snorlax come muchísimos kilos de comida al día. Lo único que hará será echarse a dormir hasta que vuelva a despertarse por el hambre. Cuando este Pokémon duerme, si por alguna razón lo despiertas, se enfadará mucho y te atacará ferozmente, aunque después de perseguirte se volverá a dormir",
        "Este Pokémon, de aspecto majestuoso, aparece en casi todos los juegos que integran la región de Kanto dentro de su recorrido. Es normalmente visto en los glaciares. Habitualmente, los Articuno tienen un sentido del honor muy desarrollado",
        "Zapdos es una de las tres aves legendarias de Kanto. Se trata de una enorme ave con un pico largo y puntiagudo con un plumaje amarillo y erizado debido a los cúmulos de electricidad que almacena en él",
        "Su nombre deriva de molten (derretido) y el número en español tres. En japonés su nombre es una romanización del inglés fire (fuego)",
        "Durante mucho tiempo se le consideró un Pokémon mítico. Vivían en grandes colonias bajo el agua y no se tuvo constancia de ello hasta hace poco. Durante años se dudó de su existencia, hasta que se encontró una colonia submarina.",
        "Cuando Dratini evoluciona, la perla de su frente se alarga hasta convertirse en un cuerno, las aletas situadas a ambos lados de la cabeza se transforman en pequeñas alas y aparecen tres esferas (una bajo la cabeza y dos más en la punta de la cola",
        "Dragonite es un gran Pokémon dragón, con varias características marcadas. Puede volar, escupir tanto fuego como agua o hielo, utilizar la electricidad, que genera mediante sus antenas pero el cómo lo hacen, es desconocido, pero podría ser porque el material del que están hechas permite reunir una enorme carga estática",
        "Mewtwo es el resultado de las ambiciones de los seres humanos en la creación de una reproducción genéticamente realzada (o más bien mejorada) de Mew",
        "La forma de Mew es derivada del gato esfinge, ya que es de aspecto felino y color rosado. Además, se dice que este Pokémon sí tiene pelo, solo que a tamaño microscópico, igual que el verdadero animal. Mew tiene grandes poderes psíquicos y los usa para esconderse o se oculta transformándose en otro Pokémon"
    };
